language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE duckboard_test;'
'/c duckboard_test'
'CREATE TABLE quacks(id SERIAL PRIMARY KEY, message VARCHAR(140), display_name VARCHAR(60), time_stamp timestamp default now());'

script:
  - bundle exec rspec
